---
title: "Friday R Bar Session"
output: html_notebook
---

This is my policy memo.

```{r chunk1, echo=FALSE}
#require("tidyverse")
library(tidyverse)
#??print - looks up documentation for function

#int = 1
#str = "hello!"
#vectors = lists
#factors = "male", "female"
#float = 1.0
#boolean = 0,1 or TRUE, FALSE


2 + 2
2 * 3
4/2
6 %% 5
4 ** 4

1 - 2*(3+1)

#8 * "r_bar"

x <- 2 * 3
```


```{r chunk2}

my_list <- c(1, 23.4 , "r bar is awesome!")

my_list[1,2]

df <- read_csv("R Bar Height and Weight - Sheet1.csv")
??read_csv
#read.csv()

glimpse(df)
str(df)
dim(df)
head(df,52)
tail(df)

df['Index'] #know its part of data frame
df$Index #interpreted as a list
df$`Height(Inches)`[10000]


#filter(df, df$`Weight(Pounds)`>100)
```

```{r}
#find the mean of height

mean(df$`Height(Inches)`, na.rm = TRUE)
max()
min()
median()
sd()
summary(df$`Height(Inches)`)

```

```{r}
library(datasets)
data(mtcars)

?lm

fits <- lm(df$`Height(Inches)` ~ df$`Weight(Pounds)`,data = df)


summary(fits)

coefficients(fits)

residuals(fits)

fitted(fits)

anova(fits)

vcov(fits)

influence(fits)

plot(df$`Height(Inches)`, df$`Weight(Pounds)`)
```

$y = \beta_{0} + \beta_{1}*Weight$
